apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodWIuZmctdGVjaC5uZXQiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiWUp0and6djN4R1Y5VFZMelhjQjR3ckkwUVV6SGJOOEIiLCJhdXRoIjoiWVdSdGFXNDZXVXAwYW5kNmRqTjRSMVk1VkZaTWVsaGpRalIzY2trd1VWVjZTR0pPT0VJPSJ9fX0=
kind: Secret
metadata:
  name: zot-regcred
  namespace: majd
type: kubernetes.io/dockerconfigjson
