apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5mZy10ZWNoLm5ldCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJZSnRqd3p2M3hHVjlUVkx6WGNCNHdySTBRVXpIYk44QiIsImF1dGgiOiJZV1J0YVc0NldVcDBhbmQ2ZGpONFIxWTVWRlpNZWxoalFqUjNja2t3VVZWNlNHSk9PRUk9In19fQ==
kind: Secret
metadata:
  name: zot-regcred
  namespace: majd
type: kubernetes.io/dockerconfigjson
